id = 'mimo-v2-flash'
name = 'Mimo-V2-Flash'
status = 'active'

[limit]
context = 256000
output = 256000

[cost]
input = 0.1
output = 0.3
cache_read = 0.01

[source]
origin = 'models_dev_github'
provider = 'qiniu-ai'

