id = 'qwen3-coder-30b-a3b-instruct'
status = 'active'
last_updated = '2026-03-17'

[limit]
context = 128000
output = 32768

[cost]
input = 0.2
output = 0.8

[source]
origin = 'models_dev_github'
provider = 'scaleway'

