id = 'anthropic--claude-3.7-sonnet'
name = 'anthropic--claude-3.7-sonnet'
status = 'deprecated'
release_date = '2025-02-24'
last_updated = '2025-02-24'

[cost]
input = 3.0
output = 15.0
cache_read = 0.3
cache_write = 3.75

[source]
origin = 'models_dev_github'
provider = 'sap-ai-core'

