id = 'qwen2.5-vl-72b-instruct'
name = 'Qwen2.5-VL-72B-Instruct'
description = 'Multimodal model for analyzing text, images, documents, and rich media'
status = 'active'
attachment = true
temperature = true
structured_output = true
open_weights = true
release_date = '2025-03-31'
last_updated = '2025-03-31'

[limit]
context = 32768
output = 32768

[modalities]
input = ['text', 'image']
output = ['text']

[cost]
input = 1.01
output = 1.01

[source]
origin = 'models_dev_github'
provider = 'ovhcloud'

