id = 'gemini-2.5-flash-preview-05-20'
name = 'Gemini 2.5 Flash 0520'
description = 'Compact GPT model for low-latency assistance and high-volume workloads'
status = 'active'
attachment = true
release_date = '2025-05-20'
last_updated = '2025-05-20'

[limit]
context = 1048000
input = 1048000
output = 65536

[modalities]
input = ['text', 'image']
output = ['text']

[cost]
input = 0.15
output = 0.6

[source]
origin = 'models_dev_github'
provider = 'nano-gpt'

