id = 'o4-mini'
status = 'active'
reasoning = true

[limit]
context = 200000
output = 100000

[modalities]
input = ['text', 'image']
output = ['text']

[cost]
input = 1.1
output = 4.4

[source]
origin = 'models_dev_github'
provider = 'abacus'

