id = 'openai-gpt-4o-2024-11-20'
name = 'GPT-4o'
status = 'active'
release_date = '2026-02-28'
last_updated = '2026-06-11'

[cost]
input = 3.125
output = 12.5

[source]
origin = 'models_dev_github'
provider = 'venice'

