id = 'qwen3-coder-480b-a35b-instruct-int4-mixed-ar'
status = 'active'
release_date = '2026-04-30'
last_updated = '2026-07-22'

[limit]
context = 106000
output = 10600

[cost]
input = 0.585
output = 2.245
cache_write = 0.2925

[source]
origin = 'models_dev_github'
provider = 'hyper'

